version: "3.7"

services:
  nginx:
    image: motion8/nginx:1.16-dev
    ports:
      - 80:80
    environment:
      APP_PORT: 8080
      APP_DNS: app
    depends_on:
      - app

  app:
    image: fastapi-bp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB_HOST: db
      POSTGRES_DB_NAME: postgres
      POSTGRES_DB_USER: postgres
      SECRET: secret
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
      - ./data:/csv_data
    image: postgres:12.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
